{{- if eq .Values.drivemgr.deployConfig true }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: loopback-config
  labels:
    app: baremetal-csi-node
data:
  config.yaml: |-
    defaultDrivePerNodeCount: {{ .Values.drivemgr.amountOfLoopDevices }}
{{- end }}

