name: e2e-testing

on:
  push:
  pull_request:
    branches: [ master, testing ]
env:
  REGISTRY: <your_docker_hub>
  CSI_BAREMETAL_DIR: <full_path_to_csi_baremetal_src>
  CSI_BAREMETAL_OPERATOR_DIR: <full_path_to_csi_baremetal_operator_src>

jobs:
  Build-csi-baremetal:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Change directory
        run: | 
          cd $CSI_BAREMETAL_DIR 
          export CSI_VERSION=`make version`

      - name: Get dependencies
        run: make dependency

      - name: Compile proto files
        run: make install-compile-proto

      - name: Generate CRD
        run: |
          make install-controller-gen 
          make generate-deepcopy

      - name: Run unit tests
        run: make test

      - name: Run sanity tests
        run: make test-sanity

      - name: Run linting
        run: make lint

      - name: Build binary
        run: |
          make build
          make DRIVE_MANAGER_TYPE=loopbackmgr build-drivemgr

      - name:  Build docker images
        run: |
          make images REGISTRY=$REGISTRY 
          make DRIVE_MANAGER_TYPE=loopbackmgr image-drivemgr REGISTRY=$REGISTRY
  Build-csi-baremetal-operator:
    steps:
      - name: change directory 
        run: |
          cd $CSI_BAREMETAL_OPERATOR_DIR
          export CSI_OPERATOR_VERSION=`make version`

      - name: Run unit tests
        run: make test

      - name: Run linting
        run: make lint

      - name: Build docker image
        run: make docker-build REGISTRY=$REGISTRY
  Prepare-kind-cluster:
    steps:
      - name: change directory 
        run: cd $CSI_BAREMETAL_DIR

      - name: Build custom kind binary
        run: make kind-build

      - name: Create kind cluster
        run: make kind-create-cluster

      - name: Check cluster
        run: kubectl cluster-info --context kind-kind

      - name: Prepare sidecars 
        run: |
          make kind-pull-sidecar-images
          make deps-docker-pull
          make deps-docker-tag

      - name: Retag CSI images and load them to kind
        run: |
          make kind-tag-images TAG=$CSI_VERSION REGISTRY=$REGISTRY
          make kind-load-images TAG=$CSI_VERSION REGISTRY=$REGISTRY
          make load-operator-image OPERATOR_VERSION=$CSI_OPERATOR_VERSION REGISTRY=$REGISTRY

  Perform e2e:
    steps:
      - name: Perform e2e
        run: make test-ci CSI_VERSION=$CSI_VERSION OPERATOR_VERSION=$CSI_OPERATOR_VERSION CHARTS_DIR=$CSI_BAREMETAL_OPERATOR_DIR/charts
