name: e2e

on:
  push:
  pull_request:
    branches: [ master, testing ]

jobs:
  # e2e
  e2e:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, '[e2e]')"
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: LVL2 install
      run: |
        sudo apt-get update
        sudo apt-get install -y lvm2
    - name: CUSTOM KIND
      run: |
        wget -O kind https://github.com/painhardcore/builder/releases/download/0.0.1-alpha/kind_v0.8.1
        sudo chmod +x kind
        sudo mv kind /usr/bin
        kind create cluster --config test/kind/kind.yaml
        
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '600s'
    - name: Get kind cluster information
      run: |
          kubectl cluster-info
          kubectl get pods --all-namespaces
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}